version: "3"

services:
  backend:
    build:
      context: "backend"
      dockerfile: "Dockerfile.dev"
    ports:
      - 9000:9000

  frontend:
    build:
      context: "frontend"
      dockerfile: "Dockerfile.dev"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 8000:5173

